on: [pull_request]

name: Continuous integration

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        style: [minimal, default, all]
        rust:
          - stable
        include:
          - style: minimal
            flags: '--no-default-features'
          - style: default
            flags: ''
          - style: all
            flags: '--all-features'

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.flags }}

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all ${{ matrix.flags }} -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all ${{ matrix.flags }}
